const data = {
    products:[
        {
            _id:'1',
            name:'Ralph Lauren Yellow Slim Shirt',
            category:'Shirts',
            image:'/images/p1.webp',
            price:120,
            countInStock: 10,
            brand:'Ralph Lauren',
            rating: 5,
            numReviews:10,
            description:'High Quality Product',
        },
        {
            _id:'2',
            name:'Hollister Faded Grey Slim Shirt',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:85,
            countInStock: 20,
            brand:'Hollister',
            rating: 5,
            numReviews:10,
            description:'High Quality Product',
        },
        {
            _id:'3',
            name:'Lacoste Polo Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:175,
            countInStock: 0,
            brand:'Lacoste',
            rating: 5,
            numReviews:17,
            description:'High Quality Product',
        },
        {
            _id:'4',
            name:'Lacoste Grey Slim Pants',
            category:'Pants',
            image:'/images/p4.jpg',
            price:90,
            countInStock: 15,
            brand:'Lacoste',
            rating: 4.5,
            numReviews:14,
            description:'High Quality Product',
        },
        {
            _id:'5',
            name:'Lacoste Black Slim Pants',
            category:'Pants',
            image:'/images/p5.webp',
            price:180,
            countInStock: 5,
            brand:'Ralph Lauren',
            rating: 3,
            numReviews:10,
            description:'High Quality Product',
        },
        {
            _id:'6',
            name:'Ralph Lauren Grey Slim Pants',
            category:'Pants',
            image:'/images/p6.jpg',
            price:150,
            countInStock: 12,
            brand:'Ralph Lauren',
            rating: 5,
            numReviews:15,
            description:'High Quality Product',
        },
    ],
};

export default data;